#spring.application.name=WDA-backend
server:
  port: 8080

spring:
  datasource:

#   deployed db for production
    url: jdbc:mysql://shinkansen.proxy.rlwy.net:58559/railway
    username: root
    password: SvTfaiLrMRBvaFjrbiFfouIxaCdSzXZr

    driverClassName: "com.mysql.cj.jdbc.Driver"

#    local db for testing
#    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/WDA}
#    password: ${DBMS_PASSWORD:root}
#    username: ${DBMS_USERNAME:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true